### ISSUE TITLE
Similar to @unoverlays/vue?

### ISSUE THREAD

**Issue by hairyf** [antfu/vue-template-promise#4]
- [unoverlays](https://github.com/TuiMao233/unoverlays)

I'm talking nonsense. If it weren't for shutting it down, it's one of my projects

Using render to inject information into overlay components is more convenient (personal feeling)

>If it makes you feel uncomfortable, you can always close the issue

**Comment by antfu** [comment]
I belive they are different, just added a why section:
https://github.com/antfu/vue-template-promise#why

**Comment by hairyf** [comment]
I think I know what you mean. You don't want to create a new DLS expression UI.

Using a template is very flexible, which is a good idea.

However, if it is a highly reusable component (image selector, link selector, etc.), I may still use the render component to solve it.

Each usage has its own advantages and disadvantages, very good!

**Comment by hairyf** [comment]
`clear data` -> `open model` -> `edit data` -> `onConfirm` -> `save data` 

The above process template promise can also solve the problem by defining the status in the template component, as the template promise will be destroyed after success (if I'm not mistaken)

It can also be used in conjunction with the template component created by @unoverlays/vue, which is also good

**Comment by antoniogiroz** [comment]
Would it be interesting if this library included both approaches?
