### ISSUE TITLE
Add support for using components (SFC) or async components to useTemplatePromise.

### ISSUE THREAD

**Issue by jeremyeo** [antfu/vue-template-promise#6]
### Clear and concise description of the problem

Do we need to add this feature? The ability for useTemplatePromise to accept components or async components as arguments, without changing its main usage and syntax, could make it easier to extract complex Dialog UI into separate components.

### Suggested solution

Create a wrapper for Dialog UI to obtain type hints and slot parameters.
<img width="576" alt="image" src="https://user-images.githubusercontent.com/51736428/227619304-515fdbec-9dcd-4a12-8db1-d9794cec9f8f.png">

Write Dialog UI using a wrapper, `defineExpose({ TemplateWrapper })` is used solely to provide type information for useTemplatePromise, and currently I cannot think of any other good ways to export types from an SFC.
<img width="688" alt="image" src="https://user-images.githubusercontent.com/51736428/227619584-1f885102-8bb2-4bf8-86fc-4f3b5efef241.png">

Finally, we can use it by importing or defining async components.
<img width="628" alt="image" src="https://user-images.githubusercontent.com/51736428/227621291-5b1d4b5d-56af-4527-bddf-b9a97f9f4ad9.png">

### Alternative
Would this approach be better?
<img width="441" alt="image" src="https://user-images.githubusercontent.com/51736428/227627015-80ae70ee-79ab-44c4-a279-c232dddd1714.png">

<img width="684" alt="image" src="https://user-images.githubusercontent.com/51736428/227627129-70cd1eb4-dcbf-41cf-8660-7f3e77a470c7.png">

### Additional context

[My branch is here, and it's just a demo](https://github.com/jeremyeo/vue-template-promise/tree/feat-suppport-component)

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
Thanks for the proposal. I actually prefer the alternative solution, which looks more straightforward and already works without change. Also, one extra good aspect of it is that the component could hide the implementation details of this library, and the users do not need to know usage of this library.

**Comment by antfu** [comment]
And we could wrap with Suspense to support async components out-of-box for sure.

**Comment by jeremyeo** [comment]
Thank you for your reply. I also think the alternative solution is more appropriate and intuitive. Initially, I thought that having useTemplatePromise take over the rendering logic of the dialog would make it easier to use programmatically. However, I now feel that the native approach is more suitable. I will go ahead and close this issue.
